title: Streamdata Gallery
url: template.streamdata.gallery
tag: Template
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: template
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
leading_topics:
  - name: Market Data APIs
    body: Sources of market data available via APIs for streaming.
    url: http://market.data.api.gallery.streamdata.io/
    image: http://api.gallery.streamdata.io/assets/bw-icon-market-data.png
  - name: Machine Learning APIs
    body: Some machine learning APIs that can be used to augment streaming data APIs.
    url: http://machine.learning.api.gallery.streamdata.io/
    image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-machine-learning.png
  - name: News APIs
    body: Exploring the available news APIs for turning into real time streams.
    url: http://news.api.gallery.streamdata.io/
    image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-news-icon.png
  - name: Social APIs
    body: Going to the source of social data, and streaming social network APIs.
    url: http://social.api.gallery.streamdata.io/
    image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-social-network.png
  - name: Weather APIs
    body: Tuning into the weeather around us and our customers using APIs.
    url: http://weather.api.gallery.streamdata.io/
    image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-weather.png
  - name: Photos APIs
    body: The photo APIs that are dominating the landscape for storage and delivery.
    url: http://photos.api.gallery.streamdata.io/
    image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-photo.png
  - name: Events APIs
    body: Tuning into the different types of events APIs are used to deliver upon.
    url: http://events.api.gallery.streamdata.io/
    image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-calendar.png
  - name: Video APIs
    body: Known where to find and manage videos across a variety of platforms.
    url: http://videos.api.gallery.streamdata.io/
    image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-video.png
  - name: Blockchain APIs
    body: Tuning into blockchain, and the crypocurrency realm using web APIs.
    url: http://blockchain.api.gallery.streamdata.io/
    image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-blockchain.png
